name: "Create Squeak Image"
description: "Create and prepare a customized all-in-one image for the latest Trunk version of Squeak"
inputs:
  prepare-script:
    description: "Path to `.st` file that will be executed before saving the image"
    required: false
  postpare-script:
    description: "Path to `.st` file that will be executed when the image is opened again"
    required: false
branding:
  icon: box
  color: white

outputs:
  bundle-path:
    description: "Path to created image bundle"
    value: ${{ steps.createImage.outputs.bundle-path }}
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v2
  - id: smalltalkci
    uses: hpi-swa/setup-smalltalkCI@v1
    with:
      smalltalk-image: Squeak64-Trunk
  - id: createImage
    run: ${{ github.action_path }}/create_image.sh
    shell: bash
    env:
      PREPARE_SCRIPT: ${{ inputs.prepare-script }}
      POSTPARE_SCRIPT: ${{ inputs.postpare-script }}
