name: "Create Image"
description: "Create and prepare a customized Squeak all-in-one image"
inputs:
  squeak-version:
    description: "The version of Squeak to be used"
    required: true
  squeak-bitness:
    description: "The bitness of the image to be created"
    required: false
    default: "64"
  prepare-script:
    description: "Path to `.st` file that will be executed before saving the image"
    required: false
  postpare-script:
    description: "Path to `.st` file that will be executed when the image is opened again"
    required: false
branding:
  icon: box
  color: white

outputs:
  bundle-path:
    description: "Path to created image bundle"
    value: ${{ steps.create-image.outputs.bundle-path }}
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v2
  - id: smalltalkci
    uses: hpi-swa/setup-smalltalkCI@v1
    with:
      smalltalk-image: Squeak64-Trunk
  - id: create-image
    run: ${{ github.action_path }}/src/create_image.sh
    shell: bash
    env:
      SQUEAK_VERSION: ${{ inputs.squeak-version }}
      SQUEAK_BITNESS: ${{ inputs.squeak-bitness }}
      PREPARE_SCRIPT: ${{ inputs.prepare-script }}
      POSTPARE_SCRIPT: ${{ inputs.postpare-script }}
