name: 🧵 Lint

on:
  push:
    paths: 
    - .github/workflows/lint.yml
    - '*.md'
  schedule: ['0 7 * * 1']
  workflow_dispatch:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: md-linkcheck
