name: 🧵 Lint

on:
  push:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ocular-d/md-linkcheck-action@master
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/action-shellcheck@master
