name: 🔄 Update `latest` branch

on:
  release:
    types: [published]

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git branch -f latest
        git push -f origin latest
