name: 🧪 Test

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .
        id: create-image
        with:
          prepare-script: test/prepare.st
          postpare-script: test/postpare.st
      - run: test/extract.sh "${{ steps.create-image.outputs.bundle-path }}"
      - run: src/prepare_script.sh output/image/squeak.sh
      - run: output/image/squeak.sh "$(realpath test/test.st)"
